import type { Metadata } from "next";
import "@/src/app/globals.css";
import "../app/globals.css";
import { Inter, Suwannaphum } from "next/font/google";
import NoInternet from "./no-internet";

const suwannaphum = Suwannaphum({
  subsets: ["khmer"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function PublicUserLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
      <body className={`${suwannaphum.className} ${inter} antialiased`}>
        {/* No Internet page will be shown when the user is offline */}
        <NoInternet/>
        <main className="w-full"> {children}</main>
      </body>
    </html>
    );
  }
  
