// // src/app/public_user/layout.tsx
// import "@/src/app/globals.css";
// import type { Metadata } from "next";
// import "../globals.css";
// import { Inter, Suwannaphum } from "next/font/google";
// import SideBarProfileComponent from "@/src/components/ProfileComponent/SideBarProfileComponent";
// const suwannaphum = Suwannaphum({
//   subsets: ["khmer"],
//   weight: ["400", "700"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export default function ProfileLayout({
//     children,
//   }: {
//     children: React.ReactNode;
//   }) {
//     return (
//       <html lang="en">
//       <body className={`bg-[#F3FBF9] ${suwannaphum} ${inter} antialiased` }>
//        <div className="flex w-full  lg:flex-row h-fit lg:h-screen bg-[#F3FBF9] max-w-8xl mx-auto md:my-6">
//           {/* Sidebar */}
//           <aside className="lg:w-1/3 h-24 p-7  w-fit">
//             <SideBarProfileComponent />
//           </aside>

//           {/* Main Content */}
//           <main className="lg:w-2/3 w-full py-8 px-7 ">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//     );
//   }

// src/app/public_user/layout.tsx
// import "@/src/app/globals.css";
// import type { Metadata } from "next";
// import "../globals.css";
// import { Inter, Suwannaphum } from "next/font/google";
// import SideBarProfileComponent from "@/src/components/ProfileComponent/SideBarProfileComponent";
// const suwannaphum = Suwannaphum({
//   subsets: ["khmer"],
//   weight: ["400", "700"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function ProfileLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`bg-[#F3FBF9] ${suwannaphum} ${inter} antialiased`}
//       >
//         <div className="flex w-full lg:flex-row h-screen bg-[#F3FBF9] max-w-8xl mx-auto md:my-6 pt-20"> {/* Added pt-20 to offset the fixed header */}
//           {/* Sidebar */}
//           <aside className="lg:w-1/3 h-24 p-7 w-fit">
//             <SideBarProfileComponent />
//           </aside>

//           {/* Main Content */}
//           <main className="lg:w-2/3 w-full py-8 px-7">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }


// src/app/public_user/layout.tsx
import "@/src/app/globals.css";
import type { Metadata } from "next";
import "../globals.css";
import { Inter, Suwannaphum } from "next/font/google";
import SideBarProfileComponent from "@/src/components/ProfileComponent/SideBarProfileComponent";
const suwannaphum = Suwannaphum({
  subsets: ["khmer"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-[#F3FBF9] ${suwannaphum} ${inter} antialiased`}
      >
        <div className="flex  w-full lg:flex-row h-screen  max-w-8xl mx-auto  m-0">
          {/* Sidebar */}
          <aside className="xl:w-1/4 xl:m-20 2xl:ml-11 lg:w-1/4 lg:m-20 ">
            <SideBarProfileComponent />
          </aside>

          {/* Main Content */}
          <main className="xl:w-3/4 w-full py-8 px-8 lg:w-3/4">{children}</main>
        </div>
      </body>
    </html>
  );
}
